import Link from 'next/link'
import { Button } from '@/components/ui/Button'

export const metadata = {
  title: 'Terms of Service — BuildReady Blueprint',
  description: 'Terms for using BuildReady Blueprint.',
}

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-2xl px-4 py-20">
      <h1 className="font-display text-3xl font-bold text-gray-900">Terms of Service</h1>
      <p className="mt-2 text-sm text-gray-500">Last updated: July 2026</p>

      <div className="mt-8 space-y-6 text-sm leading-relaxed text-gray-700">
        <section>
          <h2 className="font-display text-lg font-semibold text-gray-900">Usage</h2>
          <p className="mt-2">BuildReady Blueprint provides AI-generated website blueprints for your personal or business use. You may use generated blueprints to build your own websites. You may not resell or redistribute the blueprints as-is.</p>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold text-gray-900">Purchases</h2>
          <p className="mt-2">Blueprint Kit ($49) and Pro Prompt Kit ($99) are one-time purchases. Payments are processed by Stripe. Due to the digital nature of the product, refunds are handled on a case-by-case basis.</p>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold text-gray-900">AI-generated content</h2>
          <p className="mt-2">Blueprints are generated by AI and may contain inaccuracies. You are responsible for reviewing and adapting the content before publishing. BuildReady Blueprint is not liable for outcomes from using generated content.</p>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold text-gray-900">Contact</h2>
          <p className="mt-2">Questions? Email hello@stellio.com.au</p>
        </section>
      </div>

      <div className="mt-12">
        <Link href="/"><Button variant="ghost">Back to home</Button></Link>
      </div>
    </div>
  )
}
